services:
  - type: web
    name: my-web-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: "10000"  # Hoặc cổng Render chỉ định
